### ISSUE TITLE
View and Copy CSS Changes 

### ISSUE THREAD

**Issue by karlcow** [pankajparashar/canidev.tools#72]
Both Firefox and Safari give access to the changes done to a CSS. 

Safari (View): 

<img width="622" alt="Screenshot 2022-10-20 at 13 20 53" src="https://user-images.githubusercontent.com/505230/196855725-855cf515-4064-45d9-8298-28796f7a09bb.png">

Firefox (View and Copy):

<img width="564" alt="Screenshot 2022-10-20 at 13 24 11" src="https://user-images.githubusercontent.com/505230/196856163-d50abfcd-0daf-4163-939f-26f956a41f8f.png">

```css

/* localeswitcher.built.css | https://www.apple.com/ac/localeswitcher/4/ja_JP/styles/localeswitcher.built.css */

html.ac-ls-fixed .ac-nav-overlap #main, html.ac-ls-fixed .ac-nav-overlap .main, html.ac-gn-segmentbar-visible.ac-ls-fixed .ac-nav-overlap #main, html.ac-gn-segmentbar-visible.ac-ls-fixed .ac-nav-overlap .main {
  /* margin-top: 0; */
  margin-top: 3em;
}
```
